### ISSUE TITLE
Class not registered error on desktop sample

### ISSUE THREAD

**Issue by goofcode** [microsoft/AISkillsForWindows#63]
Hi!
I'm kind of new to C++/WinRT and trying to test desktop samples with VS2017. 
I started from `VisionSkillsSamples.sln`, build and run `Desktop/ObjectDetectorSample_Desktop`.

While dealing with this issue, I found that my executable doesn't have dependencies on skill-related dlls(e.g. Microsoft.AI.Skills.SkillInterfacePreview.dll ...). I'm not sure this is related to my issue, but I expected to have those dependencies.

Please let me know if I missed any configuration required.
Thank you!

+ I had to run unblock-file on prebuild and postbuild scripts to make them work.

**Comment by LPBourret** [comment]
sounds like you were unblocked, indeed the pre and post build steps are important to ingest manifest and leverage reg-free activation of COM components exposed by the AI Skills WinRT Runtime Components in the NuGet packages
